### ISSUE TITLE
Error with Stats v2

### ISSUE THREAD

**Issue by elreco** [iXyles/fortnite-basic-api#12]
Hello,

I got a new error : 

`(node:15800) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Function.convertV2 (/home/brotoxic/sites/fortniteapi/node_modules/fortnite-basic-api/src/Client/StatsConverter.js:76:12)
    at Stats.getV2Stats (/home/brotoxic/sites/fortniteapi/node_modules/fortnite-basic-api/src/Client/Stats.js:57:32)
(node:15800) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 46)
`

do you know where it comes from, please?

my code : https://pastebin.com/qZZCVTEa

Thank you :)

**Comment by iXyles** [comment]
I cannot tell currently, I will take a look at it tonight and publish a fix then, unless someone made a PR fix until then.

**Comment by iXyles** [comment]
Please see comment on pull request.

**Comment by elreco** [comment]
Ok thank you
