### ISSUE TITLE
session problem

### ISSUE THREAD

**Issue by jcagz96** [iXyles/fortnite-basic-api#14]
Is it possible to store session and use them later ? instead of kill always kill session?

**Comment by iXyles** [comment]
Yes, just pass in "autoKill: false" in the creation of the Client see https://github.com/iXyles/fortnite-basic-api/blob/9eae06d42eb53098809d266ac8e201748a8ff7c7/example-test/index.js#L10

**Comment by jcagz96** [comment]
> Yes, just pass in "autoKill: false" in the creation of the Client see
> 
> https://github.com/iXyles/fortnite-basic-api/blob/9eae06d42eb53098809d266ac8e201748a8ff7c7/example-test/index.js#L10

I made that but, the message `{ success: '[fortnite-basic-api] Client session has been killed.' }` still apears: 

<a href="https://ibb.co/9TTCFqf"><img src="https://i.ibb.co/T88FVHn/Capturar.jpg" alt="Capturar" border="0"></a>

**Comment by iXyles** [comment]
Which version are you using?

**Comment by jcagz96** [comment]
> Which version are you using?

"fortnite-basic-api": "^1.3.7" 

I just runned `yarn add fortnite-basic-api`

**Comment by iXyles** [comment]
Sorry.. it seems I did an opsi, it is "autokill" not autoKill, please try again and let me know

**Comment by jcagz96** [comment]
> Sorry.. it seems I did an opsi, it is "autokill" not autoKill, please try again and let me know

yeah. it worked with `autokill: false`

Thank you for this API, I just found it today

One more question...Is possible to store the session and restore it later? I'm making a node.js API and after login I want to send session in cookies and then use that session to do more request, is it possible?

**Comment by iXyles** [comment]
Store the data from the authenticator 
```
this.expiresAt = data.expires_at;
this.accessToken = data.access_token;
this.refreshToken = data.refresh_token;
this.accountId = data.account_id;
this.perms = data.perms;
```

Then just create a Client() 
But instead of calling the login function just parse the json data to "setAuthData" in the authenticator class and you should be good to go :)
