### ISSUE TITLE
how to get playstation player stats?

### ISSUE THREAD

**Issue by jcagz96** [iXyles/fortnite-basic-api#15]
Hi,

I tried to get playstation player stats but I get this error:

<a href="https://ibb.co/mT7MPVd"><img src="https://i.ibb.co/fF7PTzZ/problem.jpg" alt="problem" border="0"></a>

When I use fortnite tracker website (https://fortnitetracker.com/) I need to pass "psn(Xhandoco)" and it works. I tried the same here but didn't worked.

So, how can I get playstation or other plataforms stats using this library?

**Comment by iXyles** [comment]
That is not a feature in fortnites api. You pass in the real epic username and not their PlayStation epic name. Or you have to pass in the ID of the account which is a GUID on the last page in settings in game.

**Comment by jcagz96** [comment]
> That is not a feature in fortnites api. You pass in the real epic username and not their PlayStation epic name. Or you have to pass in the ID of the account which is a GUID on the last page in settings in game.

but in this case "Xhandoco" is his epic username and still doesn't work

**Comment by iXyles** [comment]
Well I believe it is not because then you would have gotten a response. If he has no epic account synced with his PSN account you must insert his GUID of his account to get a result from their API. This is their limitation and nothing in my library.
