### ISSUE TITLE
Friendship error

### ISSUE THREAD

**Issue by elreco** [iXyles/fortnite-basic-api#16]
Hello,

when I try to execute the getFriends() function I got the following error 👍 

[REPORT PLEASE] [fortnite-basic-api] [Friendship] TypeError: accounts.flat is not a function
    at Lookup.lookupByUserIds (D:\DEV\laragon\www\fortniteapi\node_modules\fortnite-basic-api\src\Client\Lookup.js:83:25)
[]

Do you know why ?

thank you :)

**Comment by iXyles** [comment]
Try upgrade your Node version and let me know if it gets resolved.

**Comment by elreco** [comment]
it works! thank you
