### ISSUE TITLE
Captcha Invalid on Login attempt

### ISSUE THREAD

**Issue by ohri31** [iXyles/fortnite-basic-api#18]
Hey guys, I get this error when trying to login:

`{ error:
   { errorCode: 'errors.com.epicgames.accountportal.captcha_invalid',
     message: 'Incorrect response. Please refresh the page.' } }
{ tokenValid: false, error: 'No accessToken set' }`

I am just wondering if this can be fixed? Is there a way to fix it? I assume the worst - we won't be able to use this way to authenticate anymore as the captcha is a security aspect introduced by Epic.

**Comment by iXyles** [comment]
No issue at all. Invalid issue because this only happens when you do a lot login requests.

**Comment by iXyles** [comment]
On another note: if it is for valid bots, look into device auth in terbau's Python library fortnitepy. Should be fairly simple to implement with this. 

**Update**: This has also been integrated into this library since this comment was made.

**Comment by ohri31** [comment]
For some reason, it happens also for the newly created accounts. Anyway, thanks for the reply.

**Comment by iXyles** [comment]
Thats correct. It does not have something to do with the specific account.

**Comment by ohri31** [comment]
So it has to do with my server's IP address, did I get this correct?

**Comment by Theder** [comment]
Hi, @ohri31! Sorry for contacting you in this repo, but I can't find your email and your Fortnite-php issues are disabled.
I have an fatal error: 'UserNotFoundException: Unable to find the stats for this user. Check if the account is connected properly', but the user enter data is correct.
Do I need my own Fortnite statistic to get correct API result?
