### ISSUE TITLE
v1 returns empty data

### ISSUE THREAD

**Issue by elreco** [iXyles/fortnite-basic-api#19]
Hello,

I don't know why v1 endpoint returns empty data 

![probleme_fortnite_api1_1](https://user-images.githubusercontent.com/42843594/75091776-568d7d00-5571-11ea-89b7-5d6daa1d9577.PNG)

**Comment by iXyles** [comment]
Hey,

Epic has removed V1 stats, its now deprecated. Use v2 instead.
