### ISSUE TITLE
Exchange Code - Unauthorized

### ISSUE THREAD

**Issue by rjsnyderdesign** [iXyles/fortnite-basic-api#37]
Hello,

First of all thank you for this code.

I'm having the issue with captcha limiting so I'm trying to get the exchange code, using the below:

const exchange = await this.client.requester.sendPost(false, Endpoints.API_EXCHANGE_CODE, undefined, undefined, { 'x-xsrf-token': this.xsrf.value }, false);

I keep getting this response:
{"errorCode":"errors.com.epicgames.unauthorized","message":"You are not authenticated. Please authenticate."

From what I can tell it doesn't look like I'm supposed to have any headers besides the xsrf-token.

Am I doing something wrong? Or did the login flow change from epic?

Any help would be appreciated. Thank you for your time.

**Comment by iXyles** [comment]
Behind the "post" there is a cookiejar containing all the cookies that are required to perform the exchange request.
