### ISSUE TITLE
Getting conflict error after the login

### ISSUE THREAD

**Issue by guyng** [iXyles/fortnite-basic-api#39]
I'm getting a Conflict 409 status code response from the epiclogin method.
It was working all fine for the last few month but this error started from 2 days ago.
Anyone else had it? is there a solution for it? my account email/password did not change

**Comment by guyng** [comment]
@iXyles

**Comment by sp0xffwork** [comment]
I've got error about invalid account credentials
and can't pass deviceAuth

**Comment by guyng** [comment]
Any news? @iXyles

**Comment by iXyles** [comment]
Nothing has changed from Epics side. Login is working as expected.

**Comment by guyng** [comment]
@iXyles if i get verdict "talon" what does it mean? and how can i fix it? when i send the reputation request before the xsrf and login

**Comment by guyng** [comment]
All i need is to generate an exchange code then i can manually put it in the code but is the talon verdict fixable? do i need to change my ip? how do i get an exchange code now?

**Comment by iXyles** [comment]
I have never see the verdict Talon before, but I am assuming you are talking about login with username & password. This is basically almost impossible to do these days. You must generate a device auth token and re-use that these days. 

You can get an exchange code by other tools for example: https://github.com/ThisNils/exchange-code-generator

**Comment by guyng** [comment]
> I have never see the verdict Talon before, but I am assuming you are talking about login with username & password. This is basically almost impossible to do these days. You must generate a device auth token and re-use that these days.
> 
> You can get an exchange code by other tools for example: https://github.com/ThisNils/exchange-code-generator

Thanks man, this repository(exchange code generator) really helped me generate a new device info and with it i managed easily to get the auth token.
Thanks for the help. @iXyles
