### ISSUE TITLE
exchange code

### ISSUE THREAD

**Issue by sp0xffwork** [iXyles/fortnite-basic-api#40]
i've got login error. but getting exchange code by https://www.epicgames.com/id/login?redirectUrl=https%3A%2F%2Fwww.epicgames.com%2Fid%2Fapi%2Fexchange as i understand don't work now.

i've found script for it here https://guidedhacking.com/threads/epicgames-unofficial-api.15207/

**Comment by iXyles** [comment]
The GET method is no longer available, it was changed to POST a long time ago. You'll have to work around that and get the token through POST instead to use within the library.
