### ISSUE TITLE
Invalid accessToken after a while

### ISSUE THREAD

**Issue by Plexversal** [iXyles/fortnite-basic-api#41]
This has all been working fine up until about 2 weeks ago. The issue I'm having is `authenticator.accessToken` property just removes itself after being logged in for say 2 days or more and the application can't log in anymore without restarting. Restarting the node application resolves the error and populates the accessToken again. Is there a reason for this? Have there been any changes to the login flow recently?

**Comment by iXyles** [comment]
Hello,

This often occurs if it fails to do a refresh or a refresh token gets invalidated. The library does not automatically recall the "Login" process, but rather only doing a "checktoken" validation as you can see in the code.

If you wanna handle "logged out" / "invalidated refresh tokens" you'll have to check and handle this by yourself as the library is not. Why? Well I could implement it, but then it could end up in a forever ending loop that it tries to perform the login task with continues failure which could end up the account getting blocked/locked off. Therefore I prefer each person to handle those things manually.

Best regards.
