### ISSUE TITLE
How do you generate an exchange code?

### ISSUE THREAD

**Issue by PomegranateApps** [iXyles/fortnite-basic-api#42]
How do you generate an exchange code for the example in generatedeviceauth.js? I remember the process had something to do with logging into your Epic account with Chrome and Javascript turned off, but I can't find the instructions again.

**Comment by iXyles** [comment]
The easiest way currently is to use a tool with the switch client to get the exchange code and then insert it into the console when starting with "generate"

Examples: https://github.com/ThisNils/exchange-code-generator/releases
