### ISSUE TITLE
Using an array instead of deviceAuthPath

### ISSUE THREAD

**Issue by mahdi-rafiei** [iXyles/fortnite-basic-api#49]
Hey there,

firstly I would like to thank your for this great library that makes things easier and let us enjoy developing stuff related to this subject. I had a recommendation, which means more than a simple recommendation to me. 

Would it be possible to add an options so that we are able to just pass an array to the client and not the actual file? Because sometimes It's needed to fetch the data from the data bank.

Thank you in advance and stay safe
With best regards
Mahdi

**Comment by iXyles** [comment]
Hey,

Sorry for the delay to reply.
No, I have not, as I am always passing data to persistent storage, as I am almost always deploying things with this lib into docker containers. But I for sure understand your use-case of having it fetch from an external source as a database in your use-case.

It would be fairly easy to add such an option, however, I will not be doing it. But if you wish to add this functionality and do a PR I will gladly approve it. As long it follows the rest of the code standard of the library. Or this might be something I do during holidays when I have some extra time on the side.

BR
Marcus

**Comment by DerFortniteBoss5** [comment]
.

**Comment by DerFortniteBoss5** [comment]
Define open
