### ISSUE TITLE
Xbox Stats not working?

### ISSUE THREAD

**Issue by ChobPT** [iXyles/fortnite-basic-api#5]
Hello, I have a list of users that play on Xbox, but apparently the Xbox stats don't show, only teh ps4 and PC ones. Users are being queried by uid and username, and xbox stats show for none

**Comment by iXyles** [comment]
Hmm that sounds weird.. I am not able to test this before later afternoon, but can you print the Output of v1 stats of a xbox GUID player? :)

Preferable: pastebin/hastebin

**Comment by iXyles** [comment]
Until you can provide a GUID of a XBOX only account which fails to query, this is invalid.

Tried with several accounts from FTN and all works as expected.
