### ISSUE TITLE
Last Connection Information

### ISSUE THREAD

**Issue by Tatandiaz13** [iXyles/fortnite-basic-api#7]
Hello,
Any way to know the player's last connection?
 

Great job with the library `

**Comment by iXyles** [comment]
Hello, sorry no this is not something that is is available. What you could do is to query the stats and see when the last stats was updated in fortnite, if that might be something that fills your need.

**Comment by Tatandiaz13** [comment]
yes it's perfect for me  , but currently the stats information bring this update ? i don't see this data in the method response.

**Comment by iXyles** [comment]
There should be something in the stats that says like "latest updated" or something :)

**Comment by iXyles** [comment]
There is now an end point for this, might add it in some day.
